dist: bionic

language: csharp
solution: WeihanLi.AspNetMvc.MvcSimplePager.sln

mono: none
dotnet: 2.2.105

install:
  - dotnet restore ./CloudFlare.Client/CloudFlare.Client.csproj
  
script:
  - dotnet build /p:Configuration=Release --framework:netcoreapp2.2 ./CloudFlare.Client/CloudFlare.Client.csproj
  - dotnet test ./CloudFlare.Client.Test/CloudFlare.Client.Test.csproj
  - dotnet tool install -g coveralls.net --version 1.0.0
  - csmacnz.coveralls --help