version: '1.0.{build}'
image: 
- Visual Studio 2017
- Visual Studio 2019 Preview

branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./CloudFlare.Client.sln --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./CloudFlare.Client.sln