# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core 2.1 framework'
  inputs:
    version: 2.1.*
    packageType: 'sdk'

- task: UseDotNet@2
  displayName: 'Install .Net Core 2.2 framework'
  inputs:
    version: 2.2.*
    packageType: 'sdk'

- task: UseDotNet@2
  displayName: 'Install .Net Core 3.0 framework'
  inputs:
    version: 3.0.*

- task: UseDotNet@2
  displayName: 'Install .Net Core 3.1 framework'
  inputs:
    version: 3.1.*

- script: dotnet restore
  displayName: Restore nuget packages

- task: DotNetCoreCLI@2
  displayName: 'Build with .Net Standard 2.1 framework'
  inputs:
    command: build
    projects: 'CloudFlare.Client/CloudFlare.Client.csproj'
    arguments: '--framework:netstandard2.1 --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build with .Net Core 2.1 framework'
  inputs:
    command: build
    projects: 'CloudFlare.Client/CloudFlare.Client.csproj'
    arguments: '--framework:netcoreapp2.1 --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test with .Net Core 2.1 framework'
  inputs:
    command: test
    projects: 'CloudFlare.Client.Test/CloudFlare.Client.Test.csproj'
    arguments: '--logger trx --framework:netcoreapp2.1 --configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Build with .Net Core 2.2 framework'
  inputs:
    command: build
    projects: 'CloudFlare.Client/CloudFlare.Client.csproj'
    arguments: '--framework:netcoreapp2.2 --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test with .Net Core 2.2 framework'
  inputs:
    command: test
    projects: 'CloudFlare.Client.Test/CloudFlare.Client.Test.csproj'
    arguments: '--framework:netcoreapp2.2 --configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Build with .Net Core 3.0 framework'
  inputs:
    command: build
    projects: 'CloudFlare.Client/CloudFlare.Client.csproj'
    arguments: '--framework:netcoreapp3.0 --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test with .Net Core 3.0 framework'
  inputs:
    command: test
    projects: 'CloudFlare.Client.Test/CloudFlare.Client.Test.csproj'
    arguments: '--framework:netcoreapp3.0 --configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'Build with .Net Core 3.0 framework'
  inputs:
    command: build
    projects: 'CloudFlare.Client/CloudFlare.Client.csproj'
    arguments: '--framework:netcoreapp3.0 --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test with .Net Core 3.1 framework'
  inputs:
    command: test
    projects: 'CloudFlare.Client.Test/CloudFlare.Client.Test.csproj'
    arguments: '--framework:netcoreapp3.1 --configuration $(buildConfiguration) --collect "Code coverage"'