version: 2.0
jobs:
 build:
   docker:
     - image: microsoft/dotnet:2.1-sdk
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
            dotnet restore ./CloudFlare.Client/CloudFlare.Client.csproj
     - run:
         name: Build App
         command:
            dotnet build /CloudFlare.Client/CloudFlare.Client.csproj -c Release
